<a href="https://colab.research.google.com/github/aefajkhatik/ADVANCE-PYTHON/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a=np.array([[1,2,3,4,56]])
a

array([[ 1,  2,  3,  4, 56]])

In [12]:
e=np.array([1,2,3])
b.append([[1,2,3],[4,5,6]])
b


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [13]:
cars = ["Ford", "Volvo", "BMW"]

cars.append("Honda")

print(cars)


['Ford', 'Volvo', 'BMW', 'Honda']


In [14]:
c=np.array([[[1,2],[3,4]],[[34,6],[12,5]]])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[34,  6],
        [12,  5]]])

In [15]:
f=np.array([[1,1,2,3],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
f

array([[1, 1, 2, 3],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [16]:
#dtype
a=np.array([1,2,3],dtype=float)

In [17]:
f=np.array([[[[1,2],[3,4],[4,5],[6,7],[7,8],[9,5],[11,45],[45,22]]]])
f

array([[[[ 1,  2],
         [ 3,  4],
         [ 4,  5],
         [ 6,  7],
         [ 7,  8],
         [ 9,  5],
         [11, 45],
         [45, 22]]]])

In [18]:
#range function

a=np.arange(15,56,3)
a


array([15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54])

In [19]:
#reshape
u=np.arange(12).reshape(3,2,2)
u

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
np.ones((1,2,3))
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.arange(1,56,6)


array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55])

In [22]:
np.arange(2,10,2).reshape(2,2)

array([[2, 4],
       [6, 8]])

In [23]:
np.arange(2,50,5).reshape(2,5)

array([[ 2,  7, 12, 17, 22],
       [27, 32, 37, 42, 47]])

In [24]:
np.arange(1,50,4).reshape(1,13)

array([[ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49]])

In [25]:
np.arange(5,51,5).reshape(2,5)

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50]])

In [26]:
np.arange(5,51,5).reshape(1,10)

array([[ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [27]:
np.arange(5,51,5).reshape(10,1,)

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

In [28]:
#random
np.random.random((3,4))

array([[0.37443589, 0.04856878, 0.89133773, 0.59916191],
       [0.47576357, 0.4796161 , 0.73349896, 0.76547122],
       [0.61239647, 0.83372776, 0.76622453, 0.38469843]])

In [29]:
#linspace
np.linspace(100,2,6)

array([100. ,  80.4,  60.8,  41.2,  21.6,   2. ])

In [30]:
#np.identity
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
a=np.array([1,2,3,45,6,7,9,90])
np.ndim(a)

1

In [32]:
a=np.array([1,2,3,45,6,7,9,90])
np.shape(a)

(8,)

In [33]:
a=np.array([1,2,3,45,6,7,9,90])
np.size(a)


8

In [34]:
a=np.array([1,2,3,45,6,7,9,90])
a.dtype


dtype('int64')

In [35]:
a=np.array([1,2,3,45,6,7,9,90])
a.itemsize


8

In [36]:
a=np.array([1,2,3,45,6,7,9,90])
a.nbytes


64

In [37]:
np.random.randint(12,78,9)

array([33, 19, 34, 47, 47, 23, 73, 51, 19])

In [38]:
a=np.array([34,2,3,45,6,7,9,90])
a.shape

(8,)

In [39]:
a=np.array([[1,2,],[3,4]])
a.shape


(2, 2)

In [40]:
a=np.array([[1,2,],[3,4]])
a.size


4

In [41]:
a=np.array([[1,2,],[3,4]])
a.nbytes


32

In [42]:
a=np.array([[1,2,],[3,4]])
a.ndim


2

In [43]:
#changing database
a.astype(np.int32)
a.astype(np.float64).dtype

dtype('float64')

In [44]:
#log and exponents
y=np.array([[1,2,],[3,4]])
np.exp(y)
y

array([[1, 2],
       [3, 4]])

In [49]:
#slicing and Indexing
aj=np.array([[1,2,],[3,4]])
aj[1:2]

array([[3, 4]])

In [57]:
aj=np.array([[[1,2,3],[3,5,6]],
             [[2,65,7],[23,67,46]],
            [[12,43,54],[21,5,6]]])
aj[::1,::1]

array([[[ 1,  2,  3],
        [ 3,  5,  6]],

       [[ 2, 65,  7],
        [23, 67, 46]],

       [[12, 43, 54],
        [21,  5,  6]]])

In [58]:
aj[2::1,2::1]

array([], shape=(1, 0, 3), dtype=int64)

In [59]:
aj[1::,1::]

array([[[23, 67, 46]],

       [[21,  5,  6]]])